#if !canImport(ObjectiveC)
import XCTest

extension DataBindingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataBindingTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DataBindingTests.__allTests__DataBindingTests),
    ]
}
#endif
