name: Master

on:
  push:
    branches:
      - master
jobs:
  Test:
    name: Test
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: make clean_test
